import streamlit as st
import pandas as pd
import io
import json
import matplotlib.pyplot as plt
import seaborn as sns
from google import genai
from google.genai import types

# ==========================================
# 1. Page Config & State
# ==========================================
st.set_page_config(page_title="Agentic Data Workspace", layout="wide")
st.title("🚀 Agentic Data Science Workspace")

if "df" not in st.session_state:
    st.session_state.df = None
if "cleaning_code" not in st.session_state:
    st.session_state.cleaning_code = ""
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []
if "generated_notebook" not in st.session_state:
    st.session_state.generated_notebook = None

# ==========================================
# 2. Sidebar & Data Ingestion
# ==========================================
with st.sidebar:
    st.header("🔑 1. Configuration")
    api_key = st.text_input("Enter Gemini API Key", type="password")
    st.markdown("---")
    st.header("📂 2. Upload Data")
    uploaded_file = st.file_uploader("Upload your dataset", type=["csv"])
    
    if uploaded_file is not None and st.session_state.df is None:
        st.session_state.df = pd.read_csv(uploaded_file)
        st.success("Data loaded successfully!")
        
    if st.button("Reset Workspace"):
        st.session_state.df = None
        st.session_state.cleaning_code = ""
        st.session_state.chat_history = []
        st.session_state.generated_notebook = None
        st.rerun()

if not api_key:
    st.info("👈 Please enter your Gemini API key in the sidebar to start.")
    st.stop()

client = genai.Client(api_key=api_key)

# ==========================================
# 3. Define EDA Tools (Phase 3)
# ==========================================
def generate_histogram(column_name: str):
    df = st.session_state.df
    if column_name not in df.columns: return f"Error: '{column_name}' not found."
    fig, ax = plt.subplots(figsize=(6, 4))
    sns.histplot(df[column_name].dropna(), kde=True, ax=ax)
    st.pyplot(fig)
    return f"Rendered histogram for {column_name}."

def generate_scatter_plot(x_column: str, y_column: str):
    df = st.session_state.df
    if x_column not in df.columns or y_column not in df.columns: return "Error: Columns not found."
    fig, ax = plt.subplots(figsize=(6, 4))
    sns.scatterplot(data=df, x=x_column, y=y_column, ax=ax)
    st.pyplot(fig)
    return f"Rendered scatter plot for {x_column} vs {y_column}."

eda_tools = [generate_histogram, generate_scatter_plot]

def get_metadata(df):
    buffer = io.StringIO()
    df.info(buf=buffer)
    return f"DataFrame Info:\n{buffer.getvalue()}"

# ==========================================
# 4. Helper: Create Jupyter Notebook format
# ==========================================
def create_ipynb(python_code_string):
    """Converts a raw Python code string into a valid Jupyter Notebook (.ipynb) JSON structure"""
    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["# 🚀 Auto-Generated Deep Learning Model\n", "Generated by your Agentic Workspace."]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [line + "\n" for line in python_code_string.split('\n')]
            }
        ],
        "metadata": {},
        "nbformat": 4,
        "nbformat_minor": 5
    }
    return json.dumps(notebook, indent=1)

# ==========================================
# 5. Main Workspace Interface
# ==========================================
if st.session_state.df is not None:
    tab1, tab2, tab3 = st.tabs(["🧹 Data Cleaner", "💬 Data Chat & EDA", "🧠 Deep Learning Engine"])
    
    # --- TAB 1: The Cleaner ---
    with tab1:
        st.dataframe(st.session_state.df.head(5))
        if st.button("Generate Cleaning Code"):
            with st.spinner("Writing code..."):
                prompt = f"Write a Pandas script to clean this data based on this metadata:\n{get_metadata(st.session_state.df)}\nAssume df is loaded. Return ONLY valid Python code."
                response = client.models.generate_content(model="gemini-3.6-flash", contents=prompt)
                st.session_state.cleaning_code = response.text.replace("```python", "").replace("```", "").strip()

        if st.session_state.cleaning_code:
            st.code(st.session_state.cleaning_code, language="python")
            if st.button("Execute Code & Clean Data"):
                local_env = {"df": st.session_state.df, "pd": pd}
                exec(st.session_state.cleaning_code, local_env)
                st.session_state.df = local_env["df"]
                st.session_state.cleaning_code = ""
                st.rerun()

    # --- TAB 2: The Conversational EDA ---
    with tab2:
        for msg in st.session_state.chat_history:
            st.chat_message(msg["role"]).write(msg["content"])
            
        user_query = st.chat_input("Ask a question about the data...")
        if user_query:
            st.chat_message("user").write(user_query)
            st.session_state.chat_history.append({"role": "user", "content": user_query})
            
            with st.chat_message("assistant"):
                with st.spinner("Analyzing..."):
                    system_instruction = f"Dataset columns: {st.session_state.df.columns.tolist()}"
                    response = client.models.generate_content(
                        model="gemini-3.6-flash",
                        contents=user_query,
                        config=types.GenerateContentConfig(tools=eda_tools, system_instruction=system_instruction)
                    )
                    
                    if response.function_calls:
                        for tool_call in response.function_calls:
                            if tool_call.name == "generate_histogram":
                                generate_histogram(tool_call.args["column_name"])
                            elif tool_call.name == "generate_scatter_plot":
                                generate_scatter_plot(tool_call.args["x_column"], tool_call.args["y_column"])
                    
                    if response.text:
                        st.write(response.text)
                        st.session_state.chat_history.append({"role": "assistant", "content": response.text})

    # --- TAB 3: Deep Learning Engine (NEW) ---
    with tab3:
        st.write("### ⚙️ Automated Neural Network Builder")
        st.write("Select your target variable, and Gemini will generate a custom PyTorch training script ready for Google Colab GPUs.")
        
        col_target = st.selectbox("Select Target Variable to Predict:", st.session_state.df.columns)
        task_type = st.radio("Task Type:", ["Classification (Predict a category)", "Regression (Predict a number)"])
        
        if st.button("Generate Colab Notebook"):
            with st.spinner("Architecting Neural Network..."):
                metadata = get_metadata(st.session_state.df)
                
                dl_prompt = f"""
                You are an expert Machine Learning Engineer. I have a dataset with the following metadata:
                {metadata}
                
                I want to predict the column '{col_target}' using a Neural Network in PyTorch.
                The task is {task_type}.
                
                Write a complete, end-to-end Python script that does the following:
                1. Assumes the data is loaded as `df = pd.read_csv('your_data.csv')`.
                2. Prepares the features (X) and target (y), handling basic encodings if needed.
                3. Defines a standard PyTorch nn.Module (input size should match feature count).
                4. Writes the training loop (epochs, loss function, optimizer).
                
                Return ONLY valid Python code. No markdown formatting, no explanations.
                """
                
                dl_response = client.models.generate_content(
                    model="gemini-3.6-flash",
                    contents=dl_prompt
                )
                
                raw_code = dl_response.text.replace("```python", "").replace("```", "").strip()
                st.session_state.generated_notebook = create_ipynb(raw_code)
                
        if st.session_state.generated_notebook:
            st.success("✅ Model Architecture Generated Successfully!")
            st.download_button(
                label="📥 Download Colab Notebook (.ipynb)",
                data=st.session_state.generated_notebook,
                file_name="Auto_Generated_Model.ipynb",
                mime="application/json"
            )
            st.info("Next steps: Download this file, upload your CSV and this notebook to colab.research.google.com, and hit 'Run All'!")